


spring:
  config:
      import: optional:file:.env
  datasource:
    #url: jdbc:mysql://mysql:3306/bookglebookgle
    url: jdbc:mysql://127.0.0.1:3307/bookglebookgle

    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
