spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/bookglebookgle
    driver-class-name: org.h2.Driver
    username: root
    password: bed204!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
