server:
  port: 8081

spring:
  config:
    import: optional:env[.env]
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/bookglebookgle
    url: jdbc:mysql://localhost:3307/bookglebookgle
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
