server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: geulgwi-backend
          __path__: /logs/spring*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            thread: thread
            logger: logger
            message: message
            stack_trace: stack_trace
      - timestamp:
          source: '@timestamp'
          format: RFC3339